# SPDX-License-Identifier: MIT
"""``openbricks docs [topic]`` — read the documentation offline.

The guide pages ship inside the wheel (synced from the repo's
``docs/`` at build time — see ``setup.py::_sync_docs``), so this
works on a laptop with no internet connection and no repo checkout.

Default mode renders every guide into ONE self-contained styled HTML
file in the temp directory and opens the system browser on it, at
the requested topic's section — readable typography, real tables and
code blocks, light + dark. ``--text`` prints the raw Markdown to the
terminal instead (through ``$PAGER`` on a TTY, plainly when piped),
for ssh sessions and ``| grep``.

Only the hand-written guides are bundled. The API reference is
autodoc-generated from docstrings, so its offline equivalent is
Python's own ``help()``::

    python -c "import openbricks_sim"          # anything importable
    help(openbricks_sim)
"""

import os
import re
import subprocess
import sys
import tempfile
import webbrowser


class DocsError(Exception):
    """Raised for user-facing failures (unknown topic, missing bundle)."""


# Guide pages in reading order. Stems must match ``docs/*.md`` in the
# repo (synced verbatim into the wheel's ``_docs/``).
TOPICS = [
    "index",
    "install",
    "hardware",
    "cli",
    "simulator",
    "examples",
    "measuring",
    "architecture",
    "build",
]


def _docs_dir():
    """Locate the guide sources.

    Two valid modes, same shape as ``setup.py``'s shared-core sync:

      * Installed wheel/sdist — ``openbricks_dev/_docs/`` was bundled
        at build time.
      * Repo checkout (dev, CI tests) — read straight from the
        repo-root ``docs/``.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    bundled = os.path.join(here, "_docs")
    if os.path.isdir(bundled):
        return bundled
    checkout = os.path.normpath(
        os.path.join(here, "..", "..", "..", "docs"))
    if os.path.isdir(checkout):
        return checkout
    raise DocsError(
        "documentation pages not found: neither the bundled copy (%s) "
        "nor a repo checkout (%s) exists — broken installation?"
        % (bundled, checkout))


# ---- MyST → portable-Markdown cleanup ----------------------------------

_FRONT_MATTER = re.compile(r"\A---\n.*?\n---\n+", re.S)
# {doc}`visible text <target>` / {ref}`...` → visible text
_ROLE_WITH_TEXT = re.compile(r"\{[a-z]+\}`([^`<>]+?)\s*<[^`>]+>`")
# {class}`a.b.C` / {mod}`x` / {doc}`page` → `a.b.C` (keep code style)
_ROLE_BARE = re.compile(r"\{[a-z]+\}`([^`]+)`")
# ```{eval-rst} … ``` blocks only Sphinx can render. Two kinds appear
# in the guides; both get replaced with something useful offline.
_EVAL_RST = re.compile(r"```\{eval-rst\}\n(.*?)\n```", re.S)
_LITERALINCLUDE = re.compile(r"\.\.\s+literalinclude::\s+\S*?([^/\s]+\.py)")

_REPO_BLOB = "https://github.com/1e0ng/openbricks/blob/main/examples/"


def _replace_eval_rst(match):
    body = match.group(1)
    inc = _LITERALINCLUDE.search(body)
    if inc:
        name = inc.group(1)
        return ("*Source: [`examples/%s`](%s%s) — bundled with the "
                "repo and shown inline in the online manual.*"
                % (name, _REPO_BLOB, name))
    if ".. argparse::" in body:
        return ("*The full flag-by-flag reference is generated from "
                "the parser itself — run `openbricks --help` (or "
                "`openbricks <command> --help`), which always matches "
                "your installed version.*")
    return ("*[This section is generated by Sphinx — see the online "
            "manual at https://docs.openbricks.dev/]*")


def _clean(markdown):
    """Strip MyST front-matter, inline roles, and Sphinx-only blocks
    so the page reads well outside Sphinx (terminal or local HTML)."""
    markdown = _FRONT_MATTER.sub("", markdown)
    markdown = _EVAL_RST.sub(_replace_eval_rst, markdown)
    markdown = _ROLE_WITH_TEXT.sub(r"\1", markdown)
    markdown = _ROLE_BARE.sub(r"`\1`", markdown)
    return markdown


def _load(topic):
    path = os.path.join(_docs_dir(), topic + ".md")
    if not os.path.isfile(path):
        raise DocsError(
            "unknown topic %r — available: %s" % (topic, ", ".join(TOPICS)))
    with open(path, "r") as f:
        return _clean(f.read())


def _title(topic):
    """First ``# `` heading of the page, for the listing."""
    for line in _load(topic).splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return topic


def _emit(text):
    """Page on a terminal, plain print otherwise (pipes, tests)."""
    if sys.stdout.isatty():
        pager = os.environ.get("PAGER", "less -R")
        try:
            subprocess.run(pager.split(), input=text.encode())
            return
        except FileNotFoundError:
            pass  # no pager binary — fall through to plain print
    sys.stdout.write(text)
    if not text.endswith("\n"):
        sys.stdout.write("\n")


# ---- local HTML rendering (the default, browser-opened mode) -----------

_CSS = """
:root { --bg:#ffffff; --fg:#1e2126; --muted:#5b6069; --accent:#d9531e;
        --border:#e3ddd6; --code-bg:#f4f1ee; --pre-bg:#23272e;
        --pre-fg:#e6e1da; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#16181c; --fg:#e8e6e3; --muted:#a3a8b0;
          --border:#2e323a; --code-bg:#22262c; --pre-bg:#0f1114;
          --pre-fg:#dcd7d0; } }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",
       Roboto,Helvetica,Arial,sans-serif; }
main { max-width:52rem; margin:0 auto; padding:2rem 1.25rem 4rem; }
nav.toc { border-bottom:2px solid var(--accent); padding:1rem 0;
          margin-bottom:1rem; }
nav.toc a { margin-right:1rem; white-space:nowrap; }
a { color:var(--accent); text-decoration:none; }
a:hover { text-decoration:underline; }
h1,h2,h3 { line-height:1.25; }
section + section h1 { border-top:1px solid var(--border);
                       padding-top:2rem; margin-top:3rem; }
code { background:var(--code-bg); padding:0.1em 0.35em;
       border-radius:4px; font-size:0.9em; }
pre { background:var(--pre-bg); color:var(--pre-fg); padding:0.9rem 1rem;
      border-radius:8px; overflow-x:auto; }
pre code { background:none; padding:0; color:inherit; }
table { border-collapse:collapse; width:100%; margin:1rem 0;
        font-size:0.95em; }
th,td { border:1px solid var(--border); padding:0.4rem 0.6rem;
        text-align:left; vertical-align:top; }
th { background:var(--code-bg); }
blockquote { border-left:3px solid var(--accent); margin:1rem 0;
             padding:0.1rem 1rem; color:var(--muted); }
footer { color:var(--muted); font-size:0.85em; margin-top:3rem; }
"""


def _render_html():
    """All guides → one self-contained HTML string (nav + sections)."""
    import markdown as md
    nav = "  ".join('<a href="#%s">%s</a>' % (t, _title(t))
                    for t in TOPICS)
    sections = []
    for t in TOPICS:
        body = md.markdown(_load(t),
                           extensions=["tables", "fenced_code"])
        sections.append('<section id="%s">\n%s\n</section>' % (t, body))
    return (
        "<!DOCTYPE html>\n<html lang=\"en\"><head>"
        "<meta charset=\"utf-8\">"
        "<meta name=\"viewport\" "
        "content=\"width=device-width, initial-scale=1\">"
        "<title>openbricks documentation (offline)</title>"
        "<style>%s</style></head><body><main>"
        "<nav class=\"toc\">%s</nav>\n%s\n"
        "<footer>Rendered offline by <code>openbricks docs</code> — "
        "the full manual with the generated API reference is at "
        "<a href=\"https://docs.openbricks.dev/\">docs.openbricks.dev"
        "</a>.</footer>"
        "</main></body></html>"
        % (_CSS, nav, "\n".join(sections)))


def _open_in_browser(topic):
    path = os.path.join(tempfile.gettempdir(), "openbricks-docs.html")
    with open(path, "w") as f:
        f.write(_render_html())
    url = "file://" + path + (("#" + topic) if topic else "")
    if not webbrowser.open(url):
        raise DocsError(
            "could not open a browser (headless session?) — read in "
            "the terminal instead:  openbricks docs --text %s"
            % (topic or "<topic>"))
    print("opened %s" % url)
    return 0


def run(args):
    topic = getattr(args, "topic", None)
    if topic and topic not in TOPICS:
        # Validate before any rendering/browser side effects.
        raise DocsError(
            "unknown topic %r — available: %s" % (topic, ", ".join(TOPICS)))
    if not getattr(args, "text", False):
        return _open_in_browser(topic)
    if not topic:
        lines = ["Offline documentation topics:", ""]
        for t in TOPICS:
            lines.append("  %-14s %s" % (t, _title(t)))
        lines += [
            "",
            "Read one with:  openbricks docs --text <topic>",
            "Or drop --text to open the styled offline manual in "
            "your browser.",
            "The full manual (with API reference) is at "
            "https://docs.openbricks.dev/ — or its PDF, "
            "https://docs.openbricks.dev/openbricks-docs.pdf",
        ]
        _emit("\n".join(lines) + "\n")
        return 0
    _emit(_load(topic))
    return 0
